name: MacOs-26-openmpi
# This workflow is designed to run on MacOs
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.MD'
      - '**.md'
      - '**/.gitignore'
      - 'data/**'
      - 'joss/**'
      - 'demos/**'
      - 'docs/**'
      - 'etc/**'
      - 'man/**'
      - 'src/ff-files/**'
      - '**.png'
  pull_request:
    branches:
      - main
      - devel
    paths-ignore:
      - '**.MD'
      - '**.md'
      - '**/.gitignore'
      - 'data/**'
      - 'joss/**'
      - 'demos/**'
      - 'docs/**'
      - 'etc/**'
      - 'man/**'
      - 'src/ff-files/**'
      - '**.png'
jobs:
  build:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install gcc m4 git bison hdf5 wget autoconf automake open-mpi gmsh scotch scalapack openblas

    - name: gfortran symlink for MPI
      run: |
        ln -sfn $(brew --prefix)/bin/gfortran-15 /opt/homebrew/bin/gfortran
        which gfortran
        gfortran --version

    - name: configure
      run: |
        export SYSROOT=$(xcrun --sdk macosx --show-sdk-path)
        autoreconf -i && ./configure --prefix="${HOME}/psd" --with-dependencies=yes CC=gcc-15 CXX=g++-15 FC=gfortran-15 F77=gfortran-15
    - name: make
      run: |
        set +e                      # Don't exit immediately on failure
        export SYSROOT=$(xcrun --sdk macosx --show-sdk-path)
        make SYSROOT=$SYSROOT
        status=$?                  # Capture exit code of make
        find . \( -name "*.log" -o -name "*.txt" \) -exec rsync -R {} "$GITHUB_WORKSPACE/artifacts/" \; || true
        exit $status               # Re-raise make status to mark the step as failed if it should
    #     make install

    # - name: make check and save logs
    #   run: |
    #     set +e                      # Don't exit immediately on failure
    #     PARMMG_ACTIVE=no make check # Run make check, ignoring PARMMG_ACTIVE
    #     status=$?                  # Capture exit code of make check
    #     mkdir -p "$GITHUB_WORKSPACE/artifacts"
    #     find . \( -name "*.log" -o -name "*.txt" \) -exec cp --parents {} "$GITHUB_WORKSPACE/artifacts/" \; || true
    #     exit $status               # Re-raise make check's status to mark the step as failed if it should

    - name: Collect build artifacts
      run: |
        mkdir -p "$GITHUB_WORKSPACE/artifacts"
        find . -type f \( -name "*.log" -o -name "*.txt"  \) -exec cp --parents {} "$GITHUB_WORKSPACE/artifacts/" \; || true

    - name: Upload logs
      if: always()  # upload logs even if test failed
      uses: actions/upload-artifact@v4
      with:
        name: check-logs
        path: ${{ github.workspace }}/artifacts